In [5]:
SET1 = set("Rendika")
print(SET1)

{'a', 'i', 'k', 'e', 'R', 'n', 'd'}


In [18]:
SET2 = set([10,21,3,45,2,78,54,89])
print(SET2)

{2, 3, 10, 45, 78, 21, 54, 89}


In [26]:
SET3 = SET1 and SET2

In [38]:
SET_COBA = set([99,10,23,53,45,1,53,50])
print(type(SET_COBA))
print(set(SET_COBA))
type(SET_COBA)

<class 'set'>
{1, 50, 99, 53, 23, 10, 45}


set

In [28]:
SET3.update([10,45,84,65])
print(SET3)

{65, 2, 3, 10, 45, 78, 84, 21, 54, 89}


In [32]:
SET4 = set([10,20,32,41,12,35])
SET3.update(SET4)

print(SET3)

{65, 2, 3, 10, 12, 78, 84, 21, 20, 89, 32, 35, 41, 45, 54}


In [48]:
LIST_MULTIDIMENSI = [
["Rendika","Naruto"],
["Nurhartanto","Sasuke"],
["Suharto","Sakura"],
]
LIST_MULTIDIMENSI_2 = LIST_MULTIDIMENSI.append(SET3)
print(LIST_MULTIDIMENSI_2)

None


In [75]:
y = [0.01,1.3,5.02,10.9,18.9,28.7,40.1]
t = [0.05,0.49,1.2,1.5,2.08,2.55,3.2]

Panjang = len(y) - 1

for i in range(Panjang):
    Vi = (y[i] - y[i+1])/(t[i]-t[i+1])
    print(Vi)

2.931818181818182
5.23943661971831
19.6
13.793103448275858
20.851063829787247
17.538461538461533


In [7]:
import numpy as np

x = [[1,2],[4,6],[3,9]]

for baris in x :
    for nilai in baris :
        print("", nilai*2,end="")
    print("")
    
Transpose = np.transpose(x)
print(Transpose)

 2 4
 8 12
 6 18
[[1 4 3]
 [2 6 9]]


In [1]:
# Program to transpose a matrix using a nested loop

X = [[12,7],
    [4 ,5],
    [3 ,8]]

result = [[0,0,0],
         [0,0,0]]

# iterate through rows
for i in range(len(X)):
   # iterate through columns
   for j in range(len(X[0])):
       result[j][i] = X[i][j]

for r in result:
   print(r)


[12, 4, 3]
[7, 5, 8]


In [8]:
from numpy import*

A = array([[1.,2.],\
         [3.,4.],\
         [5.,6.]])

n,m=3,2

At = zeros ((m,n))
print (At)
for i in range (0,m):
    for j in range (0,n):
        At[i][j]=A[j][i]

print('Matriks A')
print(A)
print()

print('Matriks A Transpose')
print (At)

[[0. 0. 0.]
 [0. 0. 0.]]
Matriks A
[[1. 2.]
 [3. 4.]
 [5. 6.]]

Matriks A Transpose
[[1. 3. 5.]
 [2. 4. 6.]]


In [43]:
#input User ke List

LIST = []
        
Kolom = int(input("MASUKKAN PANJANG LIST : "))
for i in range(Kolom):
    LIST.append(int(input("Masukkan Angka Untuk Kolom Dari List Anda : ")))
print(LIST)

MASUKKAN PANJANG LIST : 3
Masukkan Angka Untuk Baris Dari List Anda : 1
Masukkan Angka Untuk Baris Dari List Anda : 23
Masukkan Angka Untuk Baris Dari List Anda : 4
[1, 23, 4]


In [63]:
from numpy import*

m = int(input("Masukkan Baris : "))
n = int(input("Masukkan Baris : "))
At = zeros ((m,n))
print (At)

Masukkan Baris : 3
Masukkan Baris : 2
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [15]:
a = int(input("Masukkan banyak Baris : "))
b = int(input("Masukkan banyak Kolom : "))

Matrix = []

for i in range(a) :
    c = []
    for j in range (b) :
        j = int(input("Masukkan angka untuk "+str(i)+" "+str(j)+" : "))
        c.append(j)
    print()
    Matrix.append(c)

print(Matrix)

for i in range (a) :
    for j in range (b) :
        print(Matrix[i][j], end = " ")
    print()

Masukkan banyak Baris : 3
Masukkan banyak Kolom : 2
Masukkan angka untuk 0 0 : 1
Masukkan angka untuk 0 1 : 2

Masukkan angka untuk 1 0 : 4
Masukkan angka untuk 1 1 : 5

Masukkan angka untuk 2 0 : 7
Masukkan angka untuk 2 1 : 8

[[1, 2], [4, 5], [7, 8]]
1 2 
4 5 
7 8 


In [3]:
Matrix = []
Baris = int(input("Masukkan Banyak Baris : "))
Kolom = int(input("Masukkan Banyak Kolom : "))

for i in range (Baris) :
    New = []
    for y in range (Kolom) :
        New.append(int(input("Masukkan Angka |Baris,Kolom| ("+str(i)+","+str(y)+") : ")))
    Matrix.extend([New])
    
for a in Matrix :
    for b in a :
        print(b, end="  ")
    print("")

Masukkan Banyak Baris : 2
Masukkan Banyak Kolom : 2
Masukkan Angka |Baris,Kolom| (0,0) : 1
Masukkan Angka |Baris,Kolom| (0,1) : 2
Masukkan Angka |Baris,Kolom| (1,0) : 4
Masukkan Angka |Baris,Kolom| (1,1) : 5
1  2  
4  5  


In [3]:
m=[] #variable matrix

b=int(input("Masukkan jumlah dimensi [baris] : ")) #baris
k=int(input("Masukkan jumlah dimensi [kolom] : ")) #kolom

print("\n",b,"X",k)

for x in range (b):
    kons=[]
    for y in range (k):
        kons.append(int(input("Masukkan Nilai : ")))
    m.extend([kons])
print(m)

Masukkan jumlah dimensi [baris] : 3
Masukkan jumlah dimensi [kolom] : 2

 3 X 2
Masukkan Nilai : 1
Masukkan Nilai : 2
Masukkan Nilai : 3
Masukkan Nilai : 4
Masukkan Nilai : 5
Masukkan Nilai : 6
[[1, 2], [3, 4], [5, 6]]


In [23]:
t = [[1,2],[4,6]]

m = []

for x in range (2) :
    kons = []
    for i in t :
        kons.append(i)
    m.extend([kons])
print(m)

[[[1, 2], [4, 6]], [[1, 2], [4, 6]]]


In [12]:
x = [[1,2],[4,6],[3,9]]

for baris in x :
    for nilai in baris :
        print("", nilai*2,end="")
    print("")

 2 4
 8 12
 6 18


Rendika Nurhartanto Suharto
(1206210011)

In [66]:
# Program untuk Transpose Matrix (No User Input)

Matrix = [[1,2],
          [4,6],
          [3,9]]

result = [[0,0,0], 
         [0,0,0]]

# iterate(Pengulangan) untuk baris
for i in range(len(Matrix)): #ngambil banyaknya matrix |[1,2],[4,6],[3,9]|
   # iterate(Pengulangan) untuk kolom
   for j in range(len(Matrix[0])): #ngambil banyaknya Matrix Index Ke-0 |[1,2]|
       result[j][i] = 2*Matrix[i][j]

for i in Matrix :  #Matrix Biasa
    print(i)
    
print(" ")

for r in result:   #Transpose Matrix
   print(r)

[1, 2]
[4, 6]
[3, 9]
 
[2, 8, 6]
[4, 12, 18]


In [21]:
Matrix = [[0,0], 
         [0,0]]

result = [[1,2],
          [4,6],]

# iterate(Pengulangan) untuk baris
for i in range(len(result)): 
   # iterate(Pengulangan) untuk kolom
   for j in range(len(result[0])): 
       Matrix[i][j] = result[j][i] 

for i in result :  #Transpose Matrix
    print(i)
    
print(" ")

for r in Matrix:   #Matrix Biasa
   print(r)

[1, 2]
[4, 6]
 
[1, 4]
[2, 6]


In [ ]:
Matrix = []
anggota = []

B = int(input("Masukkan banyak baris yang diinginkan : "))
K = int(input("Masukkan banyak kolom yang diinginkan : "))

for i in range (B) :
    print("Baris ke -", i+1)
    for y in range (K) :
        print("Masukkan Nilai Kolom ke -", y+1)
        Masuk = int(input())
        anggota.append(Masuk)
    Matrix.append(anggota)
    anggota = []

for a in Matrix :
    for b in a :
        print(b, end="  ")
    print("")
print("---------------------")