In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.22.3


In [3]:
a = np.array([1,2,3,4,5])

In [4]:
print(a)

[1 2 3 4 5]


In [5]:
print(type(a))

<class 'numpy.ndarray'>


In [6]:
b = np.array([[1,2,3],[6,7,8],[11,12,13]])

In [7]:
b

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [8]:
print(type(b))

<class 'numpy.ndarray'>


In [16]:
c = np.array([[1,2],[5,6],[9,10],[12,13]])

In [17]:
print(c)

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [12 13]]


In [18]:
c = c.astype("f")

In [19]:
print(c)

[[ 1.  2.]
 [ 5.  6.]
 [ 9. 10.]
 [12. 13.]]


In [31]:
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [32]:
print(d[1,0,0])

7


In [23]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
int32
float32


In [35]:
print(c.reshape(2,4))

[[ 1.  2.  5.  6.]
 [ 9. 10. 12. 13.]]


In [33]:
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

(5,)
(3, 3)
(4, 2)
(2, 2, 3)


In [38]:
print(d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [44]:
#Iterasi 3 Dimensi

for i in d :
    for y in i :
        for x in y :
            print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [55]:
#Iterasi 3 Dimensi dengan np.nditer(array)

for x in np.nditer(d) :
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [45]:
#Iterasi 2 Dimensi

for i in c :
    for y in i :
        print(y)

1.0
2.0
5.0
6.0
9.0
10.0
12.0
13.0


In [58]:
#Iterasi 2 Dimensi menggunakan np.nditer(array)

for x in np.nditer(c) :
    print(x)

1.0
2.0
5.0
6.0
9.0
10.0
12.0
13.0


In [64]:
# Membuat iterasi untuk bilangan aritmatika
x = 0
for i in (a) :
    x = x + i
    print(x)

1
3
6
10
15


In [73]:
#Concatenate in numpy

List1 = np.array([1,2,3,4,5])
List2 = np.array([6,7,8,9,10])
List3 = np.array([[1,2],[3,4],[5,6],[7,8]])
List4 = np.array([[9,10],[11,12],[13,14],[15,16]])
np.concatenate((List1,List2))
np.concatenate((List3,List4))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [77]:
#Split in array Numpy
List6 = np.array([1,2,3,4,5,6,7,8,9])
print(np.array_split(List6,3))

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [81]:
#Where di Numpy

List8 = np.array([1,2,3,4,5,6,7])

print(np.where(List8 == 2))

(array([1], dtype=int64),)


In [93]:
#Sort in Numpy

List7 = np.array([1,2,4,5,6,0,8,3])
print(np.sort(List7))   #Ascending
print(np.sort(List7)[::-1])   #Discending

[0 1 2 3 4 5 6 8]
[8 6 5 4 3 2 1 0]


In [98]:
# Yang bernilai True akan di tampilkan, namun yang bernilai False akan tidak ditampilkan

List9 = np.array([1,2,3,4,5])
Index = np.array([True,False,True,True,False])
print(List9[Index])

[1 3 4]


In [137]:
#Slicing 1 dimensi
List10 = np.array([1,2,3,4,5,6,7])
print(List10[1:5])  # Slicing ini index terakhir dikurangi 1 maka, index 1 sampai 4 saja yang diambil. bukan sampai 5

[2 3 4 5]


In [136]:
#Slicing 2 Dimensi

List11 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(List11[0:,0:1])

[[1]
 [4]
 [7]]
